model_repository_paths:
  - '/tmp/models'
model_name: 'detectnet'
bounding_box_scale: 35.0
bounding_box_offset: 0.0

# post filtering parameters
enable_confidence_threshold: true
enable_bbox_area_threshold: true
enable_dbscan_clustering: true
confidence_threshold: 0.35
min_bbox_area: 100.0
dbscan_confidence_threshold: 0.35
dbscan_eps: 0.7
dbscan_min_boxes: 1
dbscan_enable_athr_filter: 0
dbscan_threshold_athr: 0.0
dbscan_clustering_algorithm: 1
